### ISSUE TITLE
[Bug] Property 'width' in config isn't valid.

### ISSUE THREAD

**Issue by michidk** [glzr-io/zebar#103]
### Describe the bug

Zebar crashes when launched with default config:

![image](https://github.com/user-attachments/assets/125ccbe9-1a7e-45b2-af0c-bc26d1e252b0)

Changing the config to
```yaml
window/bar:
  providers: ['self']
  # Width of the window in physical pixels.
  width: '1337'
```
will fix it (but not with the desired behaviour of adjusting to the monitors resolution).

`zebar monitors` output:

```
PS C:\Users\michi\.glzr\zebar> zebar monitors
MONITOR_NAME="\\.\DISPLAY1" MONITOR_X="0" MONITOR_Y="0" MONITOR_WIDTH="3440" MONITOR_HEIGHT="1440" MONITOR_SCALE_FACTOR="1"
MONITOR_NAME="\\.\DISPLAY2" MONITOR_X="3440" MONITOR_Y="-220" MONITOR_WIDTH="1200" MONITOR_HEIGHT="1920" MONITOR_SCALE_FACTOR="1"
```

### Reproduction

1. Install v1.8.1 of zebar
2. Execute `zebar open bar`

### Version number

v1.8.1
