### ISSUE TITLE
[Bug] move zebar potitions 

### ISSUE THREAD

**Issue by answerwar** [glzr-io/zebar#112]
### Describe the bug

how to move zebar to botton potitions ?

### Version number

v1.8.1

**Comment by CtByte** [comment]
I assume you are using `config.yaml`

```yaml
  # Height of the window in physical pixels.
  height: '50'
  # Y-position of the window in physical pixels.
  position_y: '{{ parseInt(self.args.MONITOR_HEIGHT) - 50 }}'
```
