### ISSUE TITLE
[Feature Request] Customizable widget window title

### ISSUE THREAD

**Issue by Gerben-T** [glzr-io/zebar#142]
### Describe the problem/motivation

I would like to customize the widget's window title so i can un-ignore this one from glazewm.
Currently all the widgets have the same title; [`"Zebar"`](https://github.com/glzr-io/zebar/blob/9145098f210d2bf09eccf5ef439e9ac397703bc9/packages/desktop/src/widget_factory.rs#L200). Glazewm ignores the `"zebar"` process by default, but i don't see a way to "un-ignore" specific widget windows (without un-ignoring the whole process) because there is nothing unique between them.

### Describe the solution you'd like

Not sure what the best approach would be here, but something simple like 
```js
import * as zebar from 'https://esm.sh/zebar@2';

zebar.setWindowTitle("Some custom title");
```
would suffice

**Comment by lars-berger** [comment]
Just merged #164 which appends the relative config path to the widget's window title (e.g. `Zebar - starter/with-glazewm`)

In the next release (will be v.2.6.0), it'll also be possible to do:
```ts
import * as zebar from 'zebar';

const { window } = zebar.currentWidget();
await window.tauri.setTitle('fdsafdsa');
```

**Comment by Gerben-T** [comment]
FYI i managed to "un-ignore" a specific zebar window in glazewm using the code merged above and this glazewm config

```
window_rules:
  - commands: ['ignore']
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: 'zebar' }
        # Unignore Zebar glazewm cheatsheet window
        window_title: { regex: '^(?!(Zebar - my-custom\/cheatsheet)).*' }
```

Where `my-custom\/cheatsheet` should be your config path.
