### ISSUE TITLE
[Bug] "Config option to dock Zebar windows to monitor edge" not working when combined with GlazeWM

### ISSUE THREAD

**Issue by Gerben-T** [glzr-io/zebar#168]
### Describe the bug

I'm using GlazeWM, but when i turn on the "dock" option in zebar my windows overlap the zebar by default.

### Reproduction

Add this to GlazeWM config, so that it leaves room for the zebar
```
  # Gap between windows and the screen edge.
  outer_gap:
    top: '40px'
    right: '0px'
    bottom: '0px'
    left: '0px'
```

Start GlazeWM
Start zebar
Make sure dock option is off
Open an application 
![image](https://github.com/user-attachments/assets/e8fe4ffe-8056-45db-8b70-c7019673259c)
Press ALT+T to set the application in tiling mode (using GlazeWM)
![image](https://github.com/user-attachments/assets/8be2a00d-8085-4194-9348-5ad2c03cefc0)
Turn on zebar dock option
![image](https://github.com/user-attachments/assets/007c47e5-a2ea-4420-a978-e826a845e210)
Press ALT+T again on the application
![image](https://github.com/user-attachments/assets/e17f3f52-ba05-4527-94d2-9f2fc84defba)
Notice how it overlaps zebar.

The expectation is that the application window will be below the zebar but instead it overlaps it.

### Version number

8227e2574fcb642a9b18557baf9b2a3915f7606b
