### ISSUE TITLE
[Bug] The bar is floating

### ISSUE THREAD

**Issue by skyisthela** [glzr-io/zebar#220]
### Describe the bug

Installed zebar thru the AUR and ran it. It shows the bar but it looks like this 

![Image](https://github.com/user-attachments/assets/8cf39a5d-34f4-448a-9816-9c56546d4e29)

### Reproduction

Install zebar and run it

### Stack trace or error logs (if applicable)

```shell

```

### Version number

2.7.0

**Comment by aldrichtr** [comment]
Not sure if you are using glazeWM, but if you are, this might be because you are not "ignoring" the zebar window in your config:

```yaml
window_rules:
  - commands: ["ignore"]
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: "zebar" }
```
