### ISSUE TITLE
[Bug] Zebar `date` Provider doesn't respect `timezone`

### ISSUE THREAD

**Issue by MoaidHathot** [glzr-io/zebar#90]
### Describe the bug

The  `date` Provider doesn't respect `timezone`. Doesn't matter to what timezone I change it, it keeps showing the local timezone.
Although the `locale` config works.

### Reproduction

```yaml
    template/clock:
      providers:
        - type: 'date'
          timezone: 'IL'
      template: |
        {{ date.toFormat(date.now, 'EEE dd MMM T') }}

```

### Version number

1.8.1
