### ISSUE TITLE
[Feature Request] The title module update automatically 

### ISSUE THREAD

**Issue by DreamMaoMao** [glzr-io/zebar#97]
### Describe the problem/motivation

Currently, the title module automatically updates when the focus is changed, and zebar cannot automatically update to the latest title if the title is changed within the application.

myconfig:
```yaml
    template/title:
      styles: |
        color: #dad6ce;
        # background: #a284bf;
        font-size: 15px;
        min-width: 800px;
        align-items: center;
        text-align: center;  
      providers: ["glazewm"]
      template: |
        @if ( glazewm.focusedContainer.type === 'window') {
          <span class="current-window"> {{ glazewm.focusedContainer.title }} </span>
        } @else {
          <span class="current-window"></span>
        }
```

### Describe the solution you'd like

Automatically updated when the title within the app changes
